using Vitastic.Domain.Entities.Orders.ValueObjects;
using Vitastic.Domain.Shared.Models;
using Vitastic.Domain.Shared.Results;

namespace Vitastic.Domain.Entities.Orders;

public class OrderNote : FullEntity<OrderNoteId>
{
    #region Constants

    public const int MaxContentLength = 500;

    #endregion
    #region Properties

    public OrderId OrderId { get; private set; }

    public NoteType Type { get; private set; }

    public string Content { get; private set; }


    #endregion

    #region Constructors

    protected OrderNote() { } // EF Core

    private OrderNote(
        OrderNoteId id,
        OrderId orderId,
        NoteType type,
        string content) : base(id)
    {
        OrderId = orderId;
        Type = type;
        Content = content;
    }

    #endregion

    #region Factory

    /// <summary>
    /// Create a new OrderNote — called only from within Order aggregate.
    /// </summary>
    public static Result<OrderNote> Create(
        OrderId orderId,
        NoteType type,
        string content)
    {
        if (string.IsNullOrWhiteSpace(content))
            return OrderNoteErrors.EmptyContent;

        if (content.Length > MaxContentLength)
            return OrderNoteErrors.ContentTooLong;


        return new OrderNote(
            OrderNoteId.New(),
            orderId,
            type,
            content.Trim()
        );
    }

    #endregion
}

/// <summary>
/// Defines the type/origin of an order note.
/// </summary>
public enum NoteType
{
    /// <summary>
    /// یادداشت مشتری — Customer-facing note
    /// </summary>
    Customer = 0,

    /// <summary>
    /// یادداشت مدیر — Admin/internal note
    /// </summary>
    Admin = 1,

    /// <summary>
    /// یادداشت سیستمی — Auto-generated by domain logic
    /// </summary>
    System = 2
}
public static class OrderNoteErrors
{
    // Note content cannot be empty
    public static readonly Error EmptyContent =
        Error.Validation("OrderNote.EmptyContent", "متن یادداشت نمی‌تواند خالی باشد");

    // Note content exceeds maximum length
    public static readonly Error ContentTooLong =
        Error.Validation("OrderNote.ContentTooLong", "طول متن یادداشت بیش از حد مجاز است");
}
